In [1]:
import yfinance as yf
import pandas as pd

In [2]:
# get S&P500 tickers
tickers = pd.read_html(
    'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0].Symbol.to_list()
tickers = [x.replace('.','-') for x in tickers]

# Get the data for this tickers from yahoo finance
stock_px = yf.download(tickers,start="2019-01-01")

[*********************100%%**********************]  503 of 503 completed

In [3]:
stock_px

Price        Adj Close                                                 \
Ticker               A        AAL        AAPL        ABBV        ABNB
Date
2019-01-02   63.161678  31.963158   37.750084   68.699379         NaN
2019-01-03   60.834827  29.581665   33.989902   66.435837         NaN
2019-01-04   62.940544  31.530161   35.440899   68.576187         NaN
2019-01-07   64.277039  32.425678   35.362030   69.577087         NaN
2019-01-08   65.219299  31.904114   36.036133   69.900452         NaN
...                ...        ...         ...         ...         ...
2024-08-19  140.509995  10.310000  225.889999  196.869995  119.139999
2024-08-20  139.750000  10.290000  226.509995  196.149994  117.379997
2024-08-21  139.990005  10.400000  226.399994  196.529999  117.680000
2024-08-22  140.220001  10.140000  224.529999  196.369995  115.449997
2024-08-23  140.869995  10.390000  226.839996  197.550003  116.849998

Price                                                                   ...  \
Ticker             ABT        ACGL         ACN        ADBE         ADI  ...
Date                                                                    ...
2019-01-02   62.953056   26.190001  129.528732  224.570007   77.463654  ...
2019-01-03   59.982048   25.780001  125.106407  215.699997   72.784447  ...
2019-01-04   61.693996   26.389999  129.970993  226.190002   74.551544  ...
2019-01-07   62.617905   26.330000  130.422455  229.259995   75.020370  ...
2019-01-08   61.866104   26.430000  133.720749  232.679993   76.850578  ...
...                ...         ...         ...         ...         ...  ...
2024-08-19  111.900002  103.000000  329.440002  563.119995  225.949997  ...
2024-08-20  110.769997  102.800003  330.369995  562.250000  223.490005  ...
2024-08-21  111.389999  104.599998  333.600006  565.789978  227.500000  ...
2024-08-22  112.099998  106.510002  330.570007  557.440002  221.910004  ...
2024-08-23  112.690002  109.019997  333.269989  558.299988  228.389999  ...

Price       Volume                                                         \
Ticker         WTW       WY     WYNN      XEL       XOM      XYL      YUM
Date
2019-01-02  743800  7442000  4174400  4476100  16727200   990900  1743400
2019-01-03  689800  9788300  2885100  5287600  13866100  1243100  2680300
2019-01-04  842100  5843900  3007200  5535600  16043600   970900  2142700
2019-01-07  879200  6562200  3143800  4208100  10844200  1341600  2561100
2019-01-08  885300  6232800  2255700  3128300  11439000   912800  2604700
...            ...      ...      ...      ...       ...      ...      ...
2024-08-19  339500  3152500  3310500  2266100  12417500   751200  1671300
2024-08-20  307900  3717400  1839300  2669500  15632000   772300  1713300
2024-08-21  285800  3161200  2302300  1574000  11752400  1932300  1583200
2024-08-22  418300  3398300  1133700  1581100  10609500   898400  1393600
2024-08-23  392100  3294300  1479300  2069200  10375100   692200  1656800

Price
Ticker          ZBH     ZBRA      ZTS
Date
2019-01-02  1186663   347700  2665600
2019-01-03  1201083   514600  2390900
2019-01-04  1627812   723300  3383500
2019-01-07   927309  1100000  2360800
2019-01-08  3356770   838500  2250300
...             ...      ...      ...
2024-08-19  1003300   298900  1637000
2024-08-20   958000   431300  1186400
2024-08-21   826900   310700  1246800
2024-08-22  1164500   224900  1135800
2024-08-23   788400   196300  1247400

[1421 rows x 3018 columns]

In [4]:
stock_px.to_pickle('US_equity_px_1D.pkl')